import { Injectable, Logger } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { Octokit } from "@octokit/rest";
import {
  VcsCommentParams,
  VcsCommitStatusParams,
  VcsCreatePrParams,
  VcsPrResult,
  VcsProvider,
} from "./vcs-provider.interface";

/**
 * GitHub REST API 및 Octokit SDK 기반 VcsProvider 구현체
 */
@Injectable()
export class GitHubVcsProvider implements VcsProvider {
  readonly providerType = "GITHUB";
  private readonly logger = new Logger(GitHubVcsProvider.name);
  private readonly githubToken?: string;
  private readonly defaultRepo?: string;
  private readonly defaultBaseBranch: string;
  private readonly autoMerge: boolean;

  constructor(private readonly config: ConfigService) {
    this.githubToken =
      this.config.get<string>("GITOPS_GITHUB_TOKEN") ||
      this.config.get<string>("GITHUB_TOKEN");
    this.defaultRepo =
      this.config.get<string>("GITOPS_GITHUB_REPO") ||
      this.config.get<string>("GITHUB_REPOSITORY");
    this.defaultBaseBranch = this.config.get<string>(
      "GITOPS_GITHUB_BASE_BRANCH",
      "main",
    );
    this.autoMerge =
      this.config.get<string>("GITOPS_AUTO_MERGE", "false").toLowerCase() ===
        "true" || this.config.get<string>("GITOPS_AUTO_MERGE", "false") === "1";
  }

  /**
   * GitHub REST API를 사용하여 신규 브랜치 생성, 파일 푸시 및 PR 개설을 처리합니다.
   */
  async createPullRequest(params: VcsCreatePrParams): Promise<VcsPrResult> {
    const targetRepo = params.targetRepo || this.defaultRepo;
    const targetBaseBranch = params.targetBaseBranch || this.defaultBaseBranch;

    if (!this.githubToken || !targetRepo) {
      this.logger.warn(
        "GitHub token or repository not configured. Skipping GitHub PR creation.",
      );
      return {};
    }

    const [owner, repo] = targetRepo.split("/");
    if (!owner || !repo) {
      this.logger.warn(
        `Invalid repository format: '${targetRepo}'. Expected 'owner/repo'.`,
      );
      return {};
    }

    const branchName = `gitops/exception-${params.requestId}`;
    const commitMessage = `feat(gitops): publish PolicyException for request ${params.requestId}`;
    const prTitle = `feat(gitops): publish PolicyException manifest for request ${params.requestId}`;
    const prBody = `## 🛡️ Kyverno Governance Platform - Automated GitOps PR

* **Request ID**: \`${params.requestId}\`
* **Policy Name**: \`${params.policyName}\`
* **Target Resource**: \`${params.resourceKind}/${params.resourceName}\`
* **Namespace**: \`${params.namespace || "default"}\`
* **Target Cluster**: \`${params.clusterDisplayName || params.clusterId}\`

---
*Automated PR generated by Kyverno Governance Platform GitOps Publisher Service.*`;

    try {
      const headers = {
        Authorization: `Bearer ${this.githubToken}`,
        Accept: "application/vnd.github+json",
        "User-Agent": "Kyverno-Governance-Platform",
        "Content-Type": "application/json",
      };

      // 1. Base branch의 최신 commit SHA 조회
      const refRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${targetBaseBranch}`,
        { headers },
      );
      if (!refRes.ok) {
        throw new Error(
          `Failed to fetch base branch ref: HTTP ${refRes.status}`,
        );
      }
      const refData = (await refRes.json()) as { object?: { sha?: string } };
      const baseSha = refData.object?.sha;
      if (!baseSha) throw new Error("Base branch SHA not found.");

      // 2. 신규 브랜치 생성 (refs/heads/gitops/exception-<id>)
      const createRefRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/git/refs`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({
            ref: `refs/heads/${branchName}`,
            sha: baseSha,
          }),
        },
      );
      if (!createRefRes.ok && createRefRes.status !== 422) {
        throw new Error(`Failed to create branch: HTTP ${createRefRes.status}`);
      }

      // 3. 파일 생성/업데이트 (PUT /contents/<path>)
      let existingFileSha: string | undefined;
      const getFileRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/contents/${params.relativePath}?ref=${branchName}`,
        { headers },
      );
      if (getFileRes.ok) {
        const fileData = (await getFileRes.json()) as { sha?: string };
        existingFileSha = fileData.sha;
      }

      const putBody: Record<string, unknown> = {
        message: commitMessage,
        content: Buffer.from(params.yamlContent, "utf8").toString("base64"),
        branch: branchName,
      };
      if (existingFileSha) {
        putBody.sha = existingFileSha;
      }

      const putFileRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/contents/${params.relativePath}`,
        {
          method: "PUT",
          headers,
          body: JSON.stringify(putBody),
        },
      );
      if (!putFileRes.ok) {
        throw new Error(`Failed to commit file: HTTP ${putFileRes.status}`);
      }

      // 4. Pull Request 개설 (POST /pulls)
      const prRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/pulls`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({
            title: prTitle,
            head: branchName,
            base: targetBaseBranch,
            body: prBody,
          }),
        },
      );

      if (!prRes.ok) {
        const errText = await prRes.text();
        this.logger.warn(
          `Failed to open PR (may already exist): HTTP ${prRes.status} - ${errText}`,
        );
        return { branchName };
      }

      const prData = (await prRes.json()) as {
        html_url?: string;
        number?: number;
      };
      const prUrl = prData.html_url;
      const prNumber = prData.number;

      this.logger.log(
        `[GitHubVcsProvider] Pull Request successfully opened: ${prUrl}`,
      );

      // 5. 옵션: Auto-Merge 시도
      if (this.autoMerge && prNumber) {
        this.mergePullRequestWithRetry(owner, repo, prNumber, headers).catch(
          (err) =>
            this.logger.warn(
              `[GitHubVcsProvider] Auto-merge failed for PR #${prNumber}: ${err.message}`,
            ),
        );
      }

      return { prUrl, prNumber, branchName };
    } catch (err) {
      this.logger.error(
        `[GitHubVcsProvider] GitHub PR workflow failed: ${(err as Error).message}`,
      );
      throw err;
    }
  }

  /**
   * PR 마크다운 코멘트를 등록합니다.
   */
  async postReviewComment(
    params: VcsCommentParams,
  ): Promise<string | undefined> {
    if (!this.githubToken) {
      this.logger.warn("GitHub token not configured. Skipping PR comment.");
      return undefined;
    }

    const [owner, repo] = params.repository.split("/");
    if (!owner || !repo) {
      this.logger.warn(`Invalid repository format: ${params.repository}`);
      return undefined;
    }

    try {
      const octokit = new Octokit({ auth: this.githubToken });
      const commentRes = await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: params.pullNumber,
        body: params.commentMarkdown,
      });

      const commentUrl = commentRes.data.html_url;
      this.logger.log(
        `Posted comment to GitHub PR #${params.pullNumber}: ${commentUrl}`,
      );
      return commentUrl;
    } catch (err) {
      this.logger.error(
        `Failed to post GitHub PR comment for #${params.pullNumber}: ${
          (err as Error).message
        }`,
      );
      return undefined;
    }
  }

  /**
   * 커밋 SHA에 Commit Status를 게시합니다.
   */
  async setCommitStatus(params: VcsCommitStatusParams): Promise<void> {
    if (!this.githubToken) {
      this.logger.warn("GitHub token not configured. Skipping commit status.");
      return;
    }

    const [owner, repo] = params.repository.split("/");
    if (!owner || !repo) {
      this.logger.warn(`Invalid repository format: ${params.repository}`);
      return;
    }

    try {
      const octokit = new Octokit({ auth: this.githubToken });
      await octokit.rest.repos.createCommitStatus({
        owner,
        repo,
        sha: params.commitSha,
        state: params.state,
        context: params.context || "kyverno/governance-gate",
        description: params.description,
        target_url: params.targetUrl,
      });

      this.logger.log(
        `Dispatched GitHub commit status '${params.state}' to ${params.commitSha.slice(0, 7)}`,
      );
    } catch (err) {
      this.logger.error(
        `Failed to create GitHub commit status for ${params.commitSha}: ${
          (err as Error).message
        }`,
      );
    }
  }

  private async mergePullRequestWithRetry(
    owner: string,
    repo: string,
    pullNumber: number,
    headers: Record<string, string>,
    maxRetries = 3,
  ): Promise<void> {
    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      try {
        const mergeRes = await fetch(
          `https://api.github.com/repos/${owner}/${repo}/pulls/${pullNumber}/merge`,
          {
            method: "PUT",
            headers,
            body: JSON.stringify({
              commit_title: `chore(gitops): auto-merge PolicyException PR #${pullNumber}`,
              merge_method: "squash",
            }),
          },
        );
        if (mergeRes.ok) {
          this.logger.log(`Auto-merged PR #${pullNumber} (attempt ${attempt})`);
          return;
        }
      } catch {
        // 재시도
      }
      await new Promise((resolve) => setTimeout(resolve, 1500 * attempt));
    }
  }
}
