# EKS 테스트 클러스터 프로비저닝을 위한 선언적 eksctl 구성 파일
# 가장 저렴한 비용과 최다 Free Tier 혜택을 지원하는 us-east-1(북버지니아) 리전 적용
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kyverno-eks-lab
  region: us-east-1
  version: "1.32"

iam:
  withOIDC: true

managedNodeGroups:
  - name: freetier-spot-nodes
    # AWS Free Plan 적격 인스턴스 (c7i-flex.large, m7i-flex.large) 및 Spot 결합으로 크레딧 소모 최소화
    instanceTypes: ["c7i-flex.large", "m7i-flex.large"]
    spot: true
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
    volumeType: gp3
    maxPodsPerNode: 110
    labels:
      environment: "test"
      role: "worker"
    tags:
      Environment: "EKS-Test"
      ManagedBy: "eksctl"

