apiVersion: v1
kind: Service
metadata:
  name: kyverno-frontend-nodeport
  namespace: kyverno-platform
  labels:
    app.kubernetes.io/name: kyverno-frontend
    app.kubernetes.io/part-of: kyverno-governance-platform
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
      name: http
  selector:
    app: kyverno-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: kyverno-backend-nodeport
  namespace: kyverno-platform
  labels:
    app.kubernetes.io/name: kyverno-backend
    app.kubernetes.io/part-of: kyverno-governance-platform
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30081
      name: http
  selector:
    app: kyverno-backend
